package com.example.musicapp.dataSong

data class Data(
    val album: Album,
    val alias: String,
    val allow_audio_ads: Boolean,
    val artists: List<ArtistX>,
    val artists_names: String,
    val composers: List<Composer>,
    val content_owner: ContentOwner,
    val created_at: Int,
    val duration: Int,
    val genres: List<Genre>,
    val has_lyric: Boolean,
    val id: String,
    val isOffical: Boolean,
    val isRBT: Boolean,
    val isVN: Boolean,
    val is_worldwide: Boolean,
    val is_zma: Boolean,
    val like: Int,
    val link: String,
    val listen: Int,
    val lyric: String,
    //val lyrics:
    val preRelease: Boolean,
    val privacy: String,
    val public_status: Int,
    val raw_id: Int,
    val released_at: Int,
    val status_code: Int,
    val status_name: String,
    val streaming: Streaming,
    val streaming_status: Int,
    val thumbnail: String,
    val thumbnail_medium: String,
    val title: String,
    val total_comment: Int,
    val user_name: String,
    val userid: Int,
    val username: String,
    val zing_choise: Boolean
)